#include "expr/node.h"
using namespace CVC4;
Node int_bvand_1_lia(Node s, Node t);
Node int_bvand_1_nia(Node s, Node t);
Node int_bvand_2_lia(Node s, Node t);
Node int_bvand_2_nia(Node s, Node t);
Node int_bvand_3_lia(Node s, Node t);
Node int_bvand_3_nia(Node s, Node t);
Node int_bvand_4_lia(Node s, Node t);
Node int_bvand_4_nia(Node s, Node t);
Node int_bvor_1_lia(Node s, Node t);
Node int_bvor_1_nia(Node s, Node t);
Node int_bvor_2_lia(Node s, Node t);
Node int_bvor_2_nia(Node s, Node t);
Node int_bvor_3_lia(Node s, Node t);
Node int_bvor_3_nia(Node s, Node t);
Node int_bvor_4_lia(Node s, Node t);
Node int_bvor_4_nia(Node s, Node t);
Node int_bvxor_1_lia(Node s, Node t);
Node int_bvxor_1_nia(Node s, Node t);
Node int_bvxor_2_lia(Node s, Node t);
Node int_bvxor_2_nia(Node s, Node t);
Node int_bvxor_3_lia(Node s, Node t);
Node int_bvxor_3_nia(Node s, Node t);
Node int_bvxor_4_lia(Node s, Node t);
Node int_bvxor_4_nia(Node s, Node t);
